### ISSUE TITLE
Roadmap v0.0.2

### ISSUE THREAD

**Issue by were** [Synthesys-Lab/assassyn#268]
As #46 is nearly done, we move to the next road map.

# Engineering Tooling

- [x] A unified IR serialization between Rust and Python
  - [x] Porting all backend generation to Python.
    - [x] Rust
    - [x] Verilog
- [x] Port Verilog to LLVM CIRCT
  - [x] PyCDE programming
  - [x] cocotb testbench
- [x] Better location hint when casting errors
  - [ ] Redundant type check in Python
  - [ ] Argument number hint in decorator
  - [ ] Stabilize the generated IR code
    - [ ] Offset identifier in Python frontend
- [ ] Easier distribution
  - [ ] Docker is still too hard to use
  - [ ] Shall we have apptainer support for this

# Better Tutorials

The existing `language.md` is little-bit out-dated

- [ ] Tentative Chaptered Tutorial in Both Chinese and English
  - [x] Basics: Driver
  - [x] A 2-Staged Pipelined Architecture
  - [ ] Explanation on Trace-based DSL
  - [ ] Cross-stage Reference: Binds
  - [ ] Cross-stage Reference: Downstream
  - [ ] Ported Writing
  - [x] Understanding the Generated u-arch
      - [x] Counter
      - [x] FIFO

# Agentic AI-friendly Refactor

- [x] #337
- [ ] Separate modules with smaller sizes (less than 400 per file)
- [x] Separate `runtime.rs` in a file generated by Python in installation flow. #338
