### ISSUE TITLE
Roadmap to v0.0.1

### ISSUE THREAD

**Issue by were** [Synthesys-Lab/assassyn#46]
# Examples

- [x] Toy examples
  - [x] A priority queue
  - [x] A systolic array: We already have one in the test case. Shall we make it bigger?
    - [x] A preliminary version is done. We are making it more realistic.
  - [x] A memory stream generator
  - [x] A single issue RISC-V core **DONE in #101 #167**

## Major Features

- [x] Support Memory access.
  - [x] Read **DONE in #54**
  - [x] Write **DONE in #65**
  - [x] Mem init by file **DONE in #95**
  - For now, DRAM and SRAM are the same except the latencies.
- [x] Support data type conversions.
- [x] Support data type larger than 64-bit.
  - [x] Make the generated rs a cargo project.
  - [x] Use `num-bigint` as our implementation. **DONE in #63**
    - [x] `concat` and `slice` supported here too.
- [x] Improve the tooling usability
   - [x] Name the dumped expressions **DONE in #67**
   - [x] Support cascade expressions **DONE in #69**
   - [x] Port the frontend to the new function attribute.
   - [ ] Better hints for Python frontend failure.
   - [x] ~Better developer documents explaining the parser development.~ Frontend port to Python.
   - ~Implicit type for unannotated integer literals.~

## Language

- [x] Make `wait-until` blocks better formalized.
  - [x] Hoist `wait-until` to the very root **DONE in #48**
  - [x] Implement a rewriter to make all the modules `wait-until` except driver and tb **DONE in #48**
  - [x] Implement a verifier to check the assumption of `wait-until` blocks.
- [x] Make FIFO better formalized.
  - [x] Make `FIFO.pop` totally implicit.
  - [x] Expose `FIFO.valid`. **DONE in PR #47**
- [x] Support inlining hierarchical synthesis in frontend. **DONE in #52**
  - [x] Separate decl and impl interface for hierarchical synthesis.
- [ ] Better documentations on language manual.
  - [x] One update #57 
- [x] Cast supported **DONE in #60**
- [ ] Support FIFO depth/latency specification.
  - [x] Make a realistic FIFO **DONE in #166**
  - [x] Expose the FIFO tuning frontend, and generate in backend.
- [x] Support cross-module combinational logic.
  - [x] Expose `triggered` of each module.
  - [x] Having a syntactical sugar for getting the predication of each value in foreign modules.
  - [x] Having a topological order of downstream combinational modules.
- [ ] Having a unified IR representation in both Rust backend and Python frontend.

## Compiler
- [x] Support multi-caller.
  - [x] Expose bind as a part of the IR **DONE in #55**
  - [x] Support partial call w/o all arguments filled.
  - [x] Dump the arbiter according to the bind redundancies.
    - [x] Manually write a round-robin arbiter. **DONE in #66**
    - [x] Compiler rewrite a round-robin arbiter. **DONE in #82**
- [x] Support common expression elimination. **DONE in #100 #106**

## Backend
- [x] Support valued-block in sv backend **DONE in #71**
- [x] Support separated r/w ports for array, allow multiple reader/writer **DONE in #92 #93**
- [x] Add assertions on array multi-writer fires
- [x] Support randomization in Rust simulator **DONE in #91**
- [x] Support all opcodes in both backends
  - [x] Verilator simulates the supported test cases. **DONE in #141**
  - [x] Simulate all the generated verilog on Verilator.

## Nits
- [x] Simplify port index in IR builder.
- [x] Fully deprecate the eager bindings.
